### ISSUE TITLE
Hacktoberfest Tags

### ISSUE THREAD

**Issue by HydraPhyzer** [HussnainAhmad1606/CodySnippets#13]
Please It Is Requested to Add these Tags in Your Repository

hacktoberfest2023
hacktoberfest
hacktober

So That This Repository Get Listed in Hacktoberfest

**Comment by itspsychocoder** [comment]
Hi, Thank you for pointing out 👏
As per hacktoberfest guidelines, previously I added hacktoberfest tag in the repo.
But I also added the tags that you have mentioned.
