### ISSUE TITLE
Feat: Redirect users to home after login/signup

### ISSUE THREAD

**Issue by akash0708** [HussnainAhmad1606/CodySnippets#6]
Currently after logging in or signing up the user stays on the same route. They should be directed to home route

**Comment by itspsychocoder** [comment]
Thank you for pointing it out 👏. Although the solution is simple, but Are you working on it?

**Comment by akash0708** [comment]
Not yet, since I wasn't assigned.

**Comment by itspsychocoder** [comment]
Ok. I have assigned this issue to you. You can work on it now 👍

**Comment by itspsychocoder** [comment]
Hi @akash0708, The issue you described has been resolved.
But, I encourage you to contribute to project by adding any other feature mentioned in README file.
Thank you for your time.

**Comment by itspsychocoder** [comment]
As the issue has been resolved, I am closing this issue
